title: 'Repositório Médico Português'
primary_color: '#000000'
secondary_color: '#ffffff'
logo: 'modules/custom/pmsr/images/cienciapt_logo_150.png'
image_1: 'modules/custom/pmsr/images/img1.jpg'
image_2: 'modules/custom/pmsr/images/img2.jpg'
image_3: 'modules/custom/pmsr/images/img3.jpg'
