title: 'Portuguese Medical of Simulation Repository'
subTitle: 'Repositório Português de Simulação Médica'
primary_color: '#ffffff'
secondary_color: '#006600'
logo: 'modules/custom/pmsr/images/cienciapt_logo_150.png'
footer_logo: 'modules/custom/pmsr/images/footer.png'
image_1: 'modules/custom/pmsr/images/img1.jpg'
image_2: 'modules/custom/pmsr/images/img2.jpg'
image_3: 'modules/custom/pmsr/images/img3.jpg'
partners_logo: 'modules/custom/pmsr/images/graxiom.png'
